# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      # boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
      availableKernelModules = ["nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci"];
      kernelModules = [];
      luks.devices."luks-365dc847-d908-41e8-a4aa-66e187960ed6" = {
        device = "/dev/disk/by-uuid/365dc847-d908-41e8-a4aa-66e187960ed6";
        allowDiscards = true;
      };
    };

    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/luks-365dc847-d908-41e8-a4aa-66e187960ed6";
      fsType = "btrfs";
      options = ["subvol=@" "compress=zstd"];
    };

    "/home" = {
      device = "/dev/mapper/luks-365dc847-d908-41e8-a4aa-66e187960ed6";
      fsType = "btrfs";
      options = ["subvol=@home" "compress=zstd"];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/34D8-0610";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
