#!/usr/bin/env bash
set -Eeuo pipefail

init_vars() {
	metadata="${NIXOS_OFFLINE_INSTALL_METADATA-}"
	cleanup_paths=()
	host=""
	target=""
	disk_override=""
	fresh_ids=0
	yes=0
	dry_run=0
}

cleanup() {
	if [ "${#cleanup_paths[@]}" -gt 0 ]; then
		rm -f -- "${cleanup_paths[@]}"
	fi
}

usage() {
	cat <<'EOF'
usage: offline-install [--target TARGET] [--disk DISK] [--fresh-ids] [--dry-run] [--yes]
       offline-install --list

Destructively install an embedded NixOS target closure.
The disko script formats and mounts the target at /mnt, then nixos-install installs
the selected system closure with --system.

--host is accepted as a compatibility alias for --target.

--disk overrides the selected target's configured disko main disk for this install
run, for example /dev/disk/by-id/nvme-...

--fresh-ids generates fresh boot/root partition UUIDs and a fresh LUKS UUID for
targets that declare those IDs, then rebuilds the selected host closure with
matching IDs before installing it.
EOF
}

list_targets() {
	printf '%s\n' "Bundled offline-install targets:"
	jq -r '.targets | to_entries[] | "        \(.key) -> host=\(.value.host) disk=\(.value.disk)"' "$metadata"
}

load_metadata() {
	if [ -z "$metadata" ]; then
		printf '%s\n' "missing required environment variable: NIXOS_OFFLINE_INSTALL_METADATA" >&2
		exit 1
	fi
	if [ ! -r "$metadata" ]; then
		printf 'offline install metadata is not readable: %s\n' "$metadata" >&2
		exit 1
	fi
	jq -e '.version == 1 and (.targets | type == "object")' "$metadata" >/dev/null
}

target_field() {
	local field target_name
	target_name="$1"
	field="$2"
	jq -er --arg target "$target_name" --arg field "$field" '.targets[$target][$field] // empty' "$metadata"
}

optional_target_field() {
	local field target_name
	target_name="$1"
	field="$2"
	jq -r --arg target "$target_name" --arg field "$field" '.targets[$target][$field] // ""' "$metadata"
}

target_host() {
	target_field "$1" host
}

target_disk() {
	target_field "$1" disk
}

disko_script() {
	target_field "$1" diskoScript
}

system_path() {
	target_field "$1" system
}

boot_part_uuid_for_target() {
	optional_target_field "$1" bootPartUuid
}

root_part_uuid_for_target() {
	optional_target_field "$1" rootPartUuid
}

luks_uuid_for_target() {
	optional_target_field "$1" luksUuid
}

select_target_if_needed() {
	local default_target target_count

	if [ -n "$target" ]; then
		return
	fi

	target_count="$(jq -r '.targets | length' "$metadata")"
	if [ "$target_count" -eq 1 ]; then
		default_target="$(jq -r '.targets | keys[0]' "$metadata")"
		target="$default_target"
		return
	fi

	list_targets
	echo
	printf 'Target to install: '
	IFS= read -r target
}

copy_repo_to_target() {
	local source
	source="$(readlink -f /etc/nixos)"

	if [ ! -d "$source" ]; then
		printf 'live /etc/nixos source is not a directory: %s\n' "$source" >&2
		exit 1
	fi

	mkdir -p /mnt/etc
	rm -rf /mnt/etc/nixos
	cp -aT "$source" /mnt/etc/nixos
	chmod -R u+w /mnt/etc/nixos
	printf '%s\n' /mnt/etc/nixos
}

nix_string() {
	jq -Rn --arg value "$1" '$value'
}

write_storage_override() {
	local boot_uuid install_disk luks_uuid override_file root_uuid target_host target_host_dir
	target_host="$1"
	install_disk="$2"
	boot_uuid="$3"
	root_uuid="$4"
	luks_uuid="$5"
	target_host_dir="/mnt/etc/nixos/hosts/$target_host"
	override_file="$target_host_dir/installer-overrides.nix"

	if [ ! -d "$target_host_dir" ]; then
		printf 'Target host config directory not found: %s\n' "$target_host_dir" >&2
		exit 1
	fi

	{
		printf '%s\n' '# Generated by offline-install. Effective storage identity for this installation.'
		printf '%s\n' '{lib, ...}:'
		printf '%s\n' 'import ../../lib/installer/storage-override.nix {'
		printf '%s\n' '  inherit lib;'
		printf '  disk = %s;\n' "$(nix_string "$install_disk")"
		if [ -n "$boot_uuid" ]; then
			printf '  bootPartUuid = %s;\n' "$(nix_string "$boot_uuid")"
		fi
		if [ -n "$root_uuid" ]; then
			printf '  rootPartUuid = %s;\n' "$(nix_string "$root_uuid")"
		fi
		if [ -n "$luks_uuid" ]; then
			printf '  luksUuid = %s;\n' "$(nix_string "$luks_uuid")"
		fi
		printf '%s\n' '}'
	} >"$override_file"

	printf '%s\n' "$override_file"
}

needs_target_rebuild() {
	[ "$configured_disk" != "$disk" ] || [ "$fresh_ids" = 1 ]
}

rebuild_target() {
	local boot_part_uuid expr_file install_disk luks_uuid root_part_uuid target_host
	local rebuilt_disko_script rebuilt_system
	target_host="$1"
	install_disk="$2"
	boot_part_uuid="$3"
	root_part_uuid="$4"
	luks_uuid="$5"

	expr_file="$(mktemp /tmp/offline-install-target.XXXXXX.nix)"
	cleanup_paths+=("$expr_file")
	{
		printf '%s\n' 'let'
		printf '%s\n' '  flake = builtins.getFlake "path:/etc/nixos";'
		printf '%s\n' '  inherit (flake.inputs.nixpkgs) lib;'
		printf '  host = (builtins.getAttr %s flake.nixosConfigurations).extendModules {\n' "$(nix_string "$target_host")"
		printf '%s\n' '    modules = ['
		printf '%s\n' '      (import /etc/nixos/lib/installer/storage-override.nix {'
		printf '%s\n' '        inherit lib;'
		printf '        disk = %s;\n' "$(nix_string "$install_disk")"
		if [ -n "$boot_part_uuid" ]; then
			printf '        bootPartUuid = %s;\n' "$(nix_string "$boot_part_uuid")"
		fi
		if [ -n "$root_part_uuid" ]; then
			printf '        rootPartUuid = %s;\n' "$(nix_string "$root_part_uuid")"
		fi
		if [ -n "$luks_uuid" ]; then
			printf '        luksUuid = %s;\n' "$(nix_string "$luks_uuid")"
		fi
		printf '%s\n' '      })'
		printf '%s\n' '    ];'
		printf '%s\n' '  };'
		printf '%s\n' 'in {'
		printf '%s\n' '  diskoScript = host.config.system.build.diskoScript;'
		printf '%s\n' '  system = host.config.system.build.toplevel;'
		printf '%s\n' '}'
	} >"$expr_file"

	rebuilt_disko_script="$(nix build --no-link --print-out-paths --file "$expr_file" diskoScript)"
	rebuilt_system="$(nix build --no-link --print-out-paths --file "$expr_file" system)"
	printf '%s\n%s\n' "$rebuilt_disko_script" "$rebuilt_system"
}

parse_args() {
	while [ "$#" -gt 0 ]; do
		case "$1" in
		--target)
			[ "$#" -ge 2 ] || {
				printf '%s\n' "--target requires a value" >&2
				exit 2
			}
			target="$2"
			shift
			;;
		--target=*)
			target="${1#--target=}"
			;;
		--host)
			[ "$#" -ge 2 ] || {
				printf '%s\n' "--host requires a value" >&2
				exit 2
			}
			target="$2"
			shift
			;;
		--host=*)
			target="${1#--host=}"
			;;
		--disk)
			[ "$#" -ge 2 ] || {
				printf '%s\n' "--disk requires a value" >&2
				exit 2
			}
			disk_override="$2"
			shift
			;;
		--disk=*)
			disk_override="${1#--disk=}"
			;;
		--fresh-ids)
			fresh_ids=1
			;;
		--list)
			list_targets
			exit 0
			;;
		--dry-run)
			dry_run=1
			;;
		--yes)
			yes=1
			;;
		--help | -h)
			usage
			exit 0
			;;
		*)
			printf 'unknown argument: %s\n' "$1" >&2
			usage >&2
			exit 2
			;;
		esac
		shift
	done
}

resolve_target() {
	select_target_if_needed

	if ! disk="$(target_disk "$target")"; then
		printf 'Unknown or non-installable target: %s\n' "$target" >&2
		list_targets >&2
		exit 2
	fi
	host="$(target_host "$target")"

	configured_disk="$disk"
	if [ -n "$disk_override" ]; then
		disk="$disk_override"
	fi

	base_script="$(disko_script "$target")"
	script="$base_script"
	system="$(system_path "$target")"
}

resolve_ids() {
	local current_boot_part_uuid current_luks_uuid current_root_part_uuid

	current_boot_part_uuid="$(boot_part_uuid_for_target "$target")"
	current_root_part_uuid="$(root_part_uuid_for_target "$target")"
	current_luks_uuid="$(luks_uuid_for_target "$target")"
	if [ "$fresh_ids" = 1 ]; then
		boot_part_uuid=""
		root_part_uuid=""
		luks_uuid=""
		if [ -n "$current_boot_part_uuid" ]; then
			boot_part_uuid="$(uuidgen | tr '[:upper:]' '[:lower:]')"
		fi
		if [ -n "$current_root_part_uuid" ]; then
			root_part_uuid="$(uuidgen | tr '[:upper:]' '[:lower:]')"
		fi
		if [ -n "$current_luks_uuid" ]; then
			luks_uuid="$(uuidgen | tr '[:upper:]' '[:lower:]')"
		fi
	else
		boot_part_uuid="$current_boot_part_uuid"
		root_part_uuid="$current_root_part_uuid"
		luks_uuid="$current_luks_uuid"
	fi
}

print_plan() {
	printf '%s\n' \
		"Install target: $target" \
		"Base host: $host" \
		"Configured disk: $configured_disk" \
		"Install disk: $disk" \
		"Disko script: $script" \
		"System path: $system"

	if [ "$fresh_ids" = 1 ]; then
		[ -n "$boot_part_uuid" ] && printf '%s\n' "Fresh boot partition UUID: $boot_part_uuid"
		[ -n "$root_part_uuid" ] && printf '%s\n' "Fresh root partition UUID: $root_part_uuid"
		[ -n "$luks_uuid" ] && printf '%s\n' "Fresh LUKS UUID: $luks_uuid"
	fi

	echo
	lsblk -o NAME,SIZE,MODEL,SERIAL,TYPE,MOUNTPOINTS
}

print_dry_run() {
	local install_system

	printf '%s\n' \
		"" \
		"Dry run only. Would run:" \
		"  $base_script"
	if [ "$configured_disk" != "$disk" ]; then
		printf '%s\n' "  # with configured disk replaced by: $disk"
	fi
	if needs_target_rebuild; then
		printf '%s\n' "  # with an effective rebuilt target closure"
		install_system="<rebuilt-system>"
	else
		install_system="$system"
	fi
	printf '%s\n' \
		"  copy /etc/nixos to /mnt/etc/nixos" \
		"  write /mnt/etc/nixos/hosts/$host/installer-overrides.nix with effective disk and UUID values" \
		"  nixos-install --root /mnt --system $install_system --no-root-passwd"
}

require_root() {
	if [ "$(id -u)" != 0 ]; then
		printf '%s\n' "Run as root." >&2
		exit 1
	fi
}

confirm_install() {
	local confirm
	if [ "$yes" = 1 ]; then
		return
	fi

	echo
	echo "This will destroy and format the disk declared above."
	printf 'Type INSTALL %s to continue: ' "$target"
	IFS= read -r confirm
	if [ "$confirm" != "INSTALL $target" ]; then
		printf '%s\n' "aborted" >&2
		exit 1
	fi
}

prepare_install_paths() {
	if needs_target_rebuild; then
		mapfile -t rebuilt_target < <(rebuild_target "$host" "$disk" "$boot_part_uuid" "$root_part_uuid" "$luks_uuid")
		script="${rebuilt_target[0]}"
		system="${rebuilt_target[1]}"
	else
		script="$base_script"
	fi
}

run_install() {
	local copied_repo storage_override
	"$script"
	copied_repo="$(copy_repo_to_target)"
	printf 'Copied repo config: %s\n' "$copied_repo"
	storage_override="$(write_storage_override "$host" "$disk" "$boot_part_uuid" "$root_part_uuid" "$luks_uuid")"
	printf 'Wrote installed storage override: %s\n' "$storage_override"
	nixos-install --root /mnt --system "$system" --no-root-passwd
}

main() {
	init_vars
	trap cleanup EXIT
	load_metadata
	parse_args "$@"
	resolve_target
	resolve_ids
	print_plan
	if [ "$dry_run" = 1 ]; then
		print_dry_run
		exit 0
	fi
	require_root
	confirm_install
	prepare_install_paths
	run_install
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
	main "$@"
fi
