keys:
  - &pvl ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIAAsB0nJcxF0wjuzXK0VTF1jbQbT24C1MM8NesCuwBb
  - &nixbot ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOVbOBRhD/RoCDHVxDGOxrTKcT5AkCBKYlHMU0q1brJP
  - &gh age15ez7aphl2ejmx29g7l4gvykw3ztgmkrdgw42t4mnzrdjz3qx65wstv8t9l
creation_rules:
  - path_regex: data/secrets/.*\.key$
    key_groups:
      - age: 
        - *pvl
        - *nixbot
        - *gh
