[formatter.alejandra]
command = "alejandra"
includes = ["**/*.nix"]

[formatter.deno]
command = "deno"
options = ["fmt"]
includes = ["*.js", "**/*.js", "*.md", "**/*.md"]

[formatter.tofu]
command = "tofu"
options = ["fmt"]
includes = ["*.tf", "**/*.tf", "*.tfvars", "**/*.tfvars"]

[formatter.rust]
command = "./scripts/rust-fmt.sh"
includes = ["pkgs/**/*.rs"]
