[formatter.alejandra]
command = "alejandra"
includes = ["**/*.nix"]

[formatter.deno]
command = "deno"
options = ["fmt"]
includes = [
  "*.md",
  "**/*.md",
  "*.json",
  "**/*.json",
  "*.jsonc",
  "**/*.jsonc",
]

[formatter.tofufmt]
command = "tofu"
options = ["fmt"]
includes = ["*.tf", "**/*.tf", "*.tfvars", "**/*.tfvars"]

[formatter.shfmt]
command = "shfmt"
options = ["-w"]
includes = ["*.sh", "**/*.sh", ".githooks/*"]
