services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "${SHADOWSOCKS_PORT}:8388/tcp"
      - "${SHADOWSOCKS_PORT}:8388/udp"
    environment:
      - METHOD=aes-256-gcm
    restart: unless-stopped
