# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      kernelModules = [];
      availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci"];
      luks.devices."luks-d01c0df8-7fa4-4a15-b7d6-497a1e37f313" = {
        device = "/dev/disk/by-uuid/d01c0df8-7fa4-4a15-b7d6-497a1e37f313";
        allowDiscards = true;
      };
    };

    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/luks-d01c0df8-7fa4-4a15-b7d6-497a1e37f313";
      fsType = "btrfs";
      options = ["subvol=@" "compress=zstd"];
    };

    "/home" = {
      device = "/dev/mapper/luks-d01c0df8-7fa4-4a15-b7d6-497a1e37f313";
      fsType = "btrfs";
      options = ["subvol=@home" "compress=zstd"];
    };

    "/swap" = {
      device = "/dev/mapper/luks-d01c0df8-7fa4-4a15-b7d6-497a1e37f313";
      fsType = "btrfs";
      options = ["subvol=@swap"];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/1C11-ED9A";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
  };

  swapDevices = [
    {
      device = "/swap/swap0";
      size = 64 * 1024; # Size in MB
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
