{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.services.host-network-qos;
  tableName = "host_network_qos";
  dscpMask = "0xfc000000";
  dscpStateMask = "0x01000000";
  preservedConnmarkMask = "0x02ffffff";
  bulkConnmark = "0x21000000";
  interfaceType = lib.types.strMatching "[a-zA-Z0-9_.-]+";
  bandwidthType = lib.types.strMatching "[1-9][0-9]*(K|M|G)?bit";
  bulkInterfaceSet = lib.concatMapStringsSep ", " (interface: ''"${interface}"'') cfg.bulkInterfaces;
  helper = pkgs.writeShellApplication {
    name = "host-network-qos";
    excludeShellChecks = ["SC1091"];
    runtimeInputs = [
      pkgs.gnugrep
      pkgs.iproute2
    ];
    text = ''
      source ${./helper.sh}
      main "$@"
    '';
  };
  serviceEnvironment = {
    HOST_NETWORK_QOS_INTERFACE = cfg.interface;
    HOST_NETWORK_QOS_IFB_INTERFACE = cfg.ifbInterface;
    HOST_NETWORK_QOS_UPLOAD_BANDWIDTH = cfg.uploadBandwidth;
    HOST_NETWORK_QOS_DOWNLOAD_BANDWIDTH = cfg.downloadBandwidth;
    HOST_NETWORK_QOS_DSCP_MASK = dscpMask;
    HOST_NETWORK_QOS_DSCP_STATE_MASK = dscpStateMask;
  };
  dispatcher = pkgs.writeShellScript "host-network-qos-dispatcher" ''
    interface="$1"
    action="$2"

    if [ "$interface" = ${lib.escapeShellArg cfg.interface} ]; then
      case "$action" in
        up | dhcp4-change | dhcp6-change | reapply)
          exec ${pkgs.systemd}/bin/systemctl --no-block try-restart host-network-qos.service
          ;;
      esac
    fi
  '';
in {
  options.services.host-network-qos = {
    enable = lib.mkEnableOption "host-priority CAKE shaping on a physical uplink";

    interface = lib.mkOption {
      type = interfaceType;
      description = "Physical uplink whose ingress and egress are shaped.";
    };

    ifbInterface = lib.mkOption {
      type = interfaceType;
      default = "ifb-${cfg.interface}";
      defaultText = lib.literalExpression ''"ifb-''${config.services.host-network-qos.interface}"'';
      description = "IFB interface used to shape traffic received from the uplink.";
    };

    uploadBandwidth = lib.mkOption {
      type = bandwidthType;
      description = "CAKE upload bandwidth, set slightly below the measured bottleneck rate.";
    };

    downloadBandwidth = lib.mkOption {
      type = bandwidthType;
      description = "CAKE download bandwidth, set slightly below the measured bottleneck rate.";
    };

    bulkInterfaces = lib.mkOption {
      type = lib.types.listOf interfaceType;
      default = [];
      description = ''
        Forwarding ingress interfaces classified into CAKE's Bulk tin. Traffic
        generated by the host remains in Best Effort.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = config.networking.nftables.enable;
        message = "services.host-network-qos requires networking.nftables.enable.";
      }
      {
        assertion = cfg.bulkInterfaces != [];
        message = "services.host-network-qos.bulkInterfaces must not be empty.";
      }
      {
        assertion = cfg.interface != cfg.ifbInterface;
        message = "services.host-network-qos.interface and ifbInterface must differ.";
      }
      {
        assertion = lib.unique cfg.bulkInterfaces == cfg.bulkInterfaces;
        message = "services.host-network-qos.bulkInterfaces must not contain duplicates.";
      }
      {
        assertion = builtins.stringLength cfg.interface <= 15;
        message = "services.host-network-qos.interface must be at most 15 characters.";
      }
      {
        assertion = builtins.stringLength cfg.ifbInterface <= 15;
        message = "services.host-network-qos.ifbInterface must be at most 15 characters.";
      }
    ];

    boot.kernelModules = [
      "act_ctinfo"
      "ifb"
      "sch_cake"
    ];

    networking = {
      nftables.tables.${tableName} = {
        family = "inet";
        content = ''
          chain forward {
            type filter hook forward priority mangle; policy accept;

            iifname { ${bulkInterfaceSet} } oifname "${cfg.interface}" meta nfproto ipv4 ip dscp set cs1 ct mark set (ct mark & ${preservedConnmarkMask}) | ${bulkConnmark}
            iifname { ${bulkInterfaceSet} } oifname "${cfg.interface}" meta nfproto ipv6 ip6 dscp set cs1 ct mark set (ct mark & ${preservedConnmarkMask}) | ${bulkConnmark}
            iifname "${cfg.interface}" oifname { ${bulkInterfaceSet} } ct mark set (ct mark & ${preservedConnmarkMask}) | ${bulkConnmark}
          }
        '';
      };

      networkmanager.dispatcherScripts = lib.mkIf config.networking.networkmanager.enable [
        {
          source = dispatcher;
          type = "basic";
        }
      ];
    };

    systemd.services.host-network-qos = {
      description = "Prioritize host traffic over forwarded guests with CAKE";
      wantedBy = ["multi-user.target"];
      wants = ["network.target"];
      after =
        [
          "network.target"
          "nftables.service"
        ]
        ++ lib.optional config.networking.networkmanager.enable "NetworkManager.service";
      restartTriggers = [helper];
      environment = serviceEnvironment;
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${helper}/bin/host-network-qos apply";
        ExecReload = "${helper}/bin/host-network-qos apply";
        ExecStop = "${helper}/bin/host-network-qos remove";
      };
    };
  };
}
