services:
  memos:
    image: docker.io/neosmemo/memos:stable
    container_name: memos
    user: 0:0
    volumes:
      - ./data/:/var/opt/memos
    ports:
      - "${MEMOS_HTTP_PORT}:5230"
    restart: unless-stopped
