# Hardware and install-storage config. Generated by host-manager.
{
  config,
  lib,
  modulesPath,
  ...
}: let
  diskoLib = import ../../lib/disko/lib.nix {lib = lib;};
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../../lib/disko
  ];

  disko.devices.disk.main = diskoLib.mkMain {
    diskDevice = "/dev/disk/by-id/nvme-SKHynix_HFS001TDE9X084N_ANA4N476110504A1C";
    boot = diskoLib.mkEfiBoot {
      size = "1G";
      partUuid = "30f09e27-d8a0-4b1e-9ae5-4f2543ca2353";
    };
    root = diskoLib.mkLuksBtrfs {
      size = "100%";
      name = "luks-696fd608-b5dc-4a8d-94ee-4925d011a449";
      luksUuid = "696fd608-b5dc-4a8d-94ee-4925d011a449";
      partUuid = "e4e7b9fc-84ee-4c7f-bb83-76465660f05e";
      subvolumes = {
        "@" = {
          mountpoint = "/";
          mountOptions = ["compress=zstd"];
        };
        "@home" = {
          mountpoint = "/home";
          mountOptions = ["compress=zstd"];
        };
        "@swap".mountpoint = "/swap";
      };
    };
  };

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci"];
      kernelModules = [];
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  swapDevices = [
    {
      device = "/swap/swap0";
      size = 65536;
    }
  ];
}
