version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    ports:
      - "${PORTAINER_HTTP_PORT}:8000"
      - "${PORTAINER_HTTPS_PORT}:9443"
    privileged: true
    volumes:
      - type: bind
        source: ${PODMAN_SOCKET}
        target: /var/run/docker.sock
      - ./data:/data
